### ISSUE TITLE
Did not find files

### ISSUE THREAD

**Issue by akadebnath** [TuyoshiVinicius/jQuery-Picture-Cut#16]
I am not sure what I am missing. Documentation says:
To test the examples is necessary to extract the folder "picture.cut" for a php environment running on a server
But in the zip file I did not find any such file/folder!
Moreover, there is no "dependencies" folder in the zip file.

In the root of zip file there is "src" folder, under which we have "windows", "php" and "img" folder. There there are other subfolders.

Need a little help here to get the thing working.

**Comment by nikbe** [comment]
Hey if you not getting folder "picture.cut" so you need some changes in "jquery.picture.cut.js" file with remove that folder location and add that file in your custom folder location.

**Comment by akadebnath** [comment]
Hey.. Thanks for replying. It turned out that the parent directory should have been named picture.cut which it was not. With some searching I found all the required folders and I have implemented this quite successfully here:
http://onedayintime.net/uploadphoto.php
Hence I closed the issue.

**Comment by nikbe** [comment]
Hey hi,
I am getting black shadow when I upload .jpg images.
